import './style.css'

document.querySelector('#app').innerHTML = `
<header class="site-header"><a class="mark" href="#top">BF<span>.</span></a><nav><a href="#work">Work</a><a href="#about">About</a><a class="nav-contact" href="mailto:Farbell755@gmail.com">Let's talk <span>&#8599;</span></a></nav></header>
<main id="top">
  <section class="hero"><p class="eyebrow">Bello Farouq / Developer &amp; creative problem solver</p><h1>I make digital<br><em>things matter.</em></h1><div class="hero-foot"><p>I build thoughtful, useful websites and digital experiences for people and businesses with something to say.</p><a class="arrow-link" href="#work">See selected work <span>&#8595;</span></a></div></section>
  <section id="work" class="work-section"><div class="section-heading"><p class="eyebrow">01 / Selected work</p><h2>A few things I have<br><em>helped bring to life.</em></h2></div><div class="project-grid">
    <article class="project project-large"><div class="project-art art-coral"><span>01</span><strong>Table<br>Ready</strong></div><div class="project-meta"><h3>Restaurant Website</h3><p>Web design / Frontend development</p><a href="#contact">View project &#8599;</a></div></article>
    <article class="project"><div class="project-art art-blue"><span>02</span><strong>Common<br>Ground</strong></div><div class="project-meta"><h3>Common Ground</h3><p>Community app / Art direction</p><a href="#contact">View project &#8599;</a></div></article>
    <article class="project"><div class="project-art art-yellow"><span>03</span><strong>Field<br>Notes</strong></div><div class="project-meta"><h3>Field Notes</h3><p>Identity system / Web design</p><a href="#contact">View project &#8599;</a></div></article>
  </div></section>
  <section id="about" class="about-section"><p class="eyebrow">02 / A little about me</p><div><h2>The best work lives<br>between <em>curiosity</em><br>and clarity.</h2><p class="about-copy">I am Bello Farouq, a developer who turns ideas into clear, memorable digital experiences. I care about the details, the big picture, and building work that is genuinely useful.</p><div class="skills"><span>Web development</span><span>Web design</span><span>Responsive interfaces</span><span>Creative problem solving</span></div></div></section>
  <section id="contact" class="contact-section"><p class="eyebrow">03 / Start a conversation</p><h2>Have a good idea?<br><em>Let's make it real.</em></h2><a class="contact-email" href="mailto:Farbell755@gmail.com">Farbell755@gmail.com <span>&#8599;</span></a></section>
</main><footer><span>Bello Farouq &copy; 2026</span><div><a href="https://github.com/Farouq123-eng/my-portfolio/" target="_blank" rel="noreferrer">GitHub &#8599;</a><a href="https://www.linkedin.com/in/bello-farouq-210197219" target="_blank" rel="noreferrer">LinkedIn &#8599;</a></div></footer>`
